typography_spectrum: 0.6078794298227876
color:
  brandColors:
    - '#1c171b'
    - '#c8c6cb'
    - '#a47352'
    - '#9b98a1'
    - '#6a46b3'
  brandStrength: 0.625
  lightness: 0.18636675458401442
  saturation: 0.375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6456343466416001
analytics:
  google: null
  facebook: null
  twitter: null
name: Foreign Morning
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: We're the first co-working community for women entrepreneurs
purpose: []
